"use client";
import { ThemeProvider } from "./Context/ThemeProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./Components/NavBar.jsx";
import Head from "next/head";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
        <Head>
          <title>Deng Benjamin | Portfolio</title>
        </Head>

        <header>
          <NavBar />
        </header>

        <main>
          <Home />
        </main>
      </ThemeProvider>
    </html>
  );
}
